"""
FORENSIC TOOLS for UFDR Query Engine.

This module provides safe, deterministic Python functions that execute parameterized SQL
against the forensic database. These tools are called by the LLM Planner when precise
filtering, pattern matching, or aggregation is required.

NO RAW SQL is generated by the LLM. The LLM only selects the tool and its arguments.
"""

import sqlite3
import json
import logging
from typing import Optional, List, Dict, Any
from datetime import datetime

from rag import DB_PATH

logger = logging.getLogger(__name__)


def _get_db():
    """Get a read-only connection to the forensic database."""
    conn = sqlite3.connect(f"file:{DB_PATH}?mode=ro", uri=True)
    conn.row_factory = sqlite3.Row
    return conn


def lookup_contacts(case_ids: List[str], name_pattern: Optional[str] = None, phone_pattern: Optional[str] = None) -> List[Dict[str, Any]]:
    """
    Find contacts matching a specific name pattern (SQL LIKE) or phone pattern.
    
    Args:
        case_ids: List of case IDs to search.
        name_pattern: Name pattern (e.g., '%Ivan%' for contains, 'Ivan%' for starts with).
        phone_pattern: Phone pattern (e.g., '%1234').
        
    Returns:
        List of contact dictionaries.
    """
    if not name_pattern and not phone_pattern:
        return []

    query = "SELECT * FROM contacts WHERE case_id IN ({})".format(",".join("?" * len(case_ids)))
    params = list(case_ids)

    if name_pattern:
        query += " AND name LIKE ?"
        params.append(name_pattern)
    
    if phone_pattern:
        query += " AND phone LIKE ?"
        params.append(phone_pattern)
        
    query += " LIMIT 100"

    try:
        with _get_db() as conn:
            cursor = conn.execute(query, params)
            results = [dict(row) for row in cursor.fetchall()]
            # Add data_type for frontend rendering
            for r in results:
                r["data_type"] = "contact"
                # Parse JSON phone numbers
                phones = []
                try:
                    if r.get("phone_numbers"):
                        phones = json.loads(r["phone_numbers"])
                        if isinstance(phones, list):
                            phones = [str(p) for p in phones]
                except Exception:
                    # Fallback if raw text
                    phones = [str(r.get("phone_numbers", ""))]
                
                # Set phone_raw for table display
                r["phone_raw"] = ", ".join(phones) if phones else ""
                
                r["text"] = f"Contact: {r.get('name', 'Unknown')} | {r.get('phone_raw', '')}"
            logger.info(f"Tool `lookup_contacts` found {len(results)} records")
            return results
    except Exception as e:
        logger.error(f"Tool execution failed: {e}")
        return []


def search_messages(
    case_ids: List[str], 
    keyword: Optional[str] = None, 
    sender: Optional[str] = None,
    limit: int = 50
) -> List[Dict[str, Any]]:
    """
    Search messages with strict filtering.
    
    Args:
        case_ids: List of case IDs.
        keyword: Text content to search (SQL LIKE %keyword%).
        sender: Sender name/number pattern.
        limit: Max results (default 50).
    """
    query = "SELECT * FROM messages WHERE case_id IN ({})".format(",".join("?" * len(case_ids)))
    params = list(case_ids)

    if keyword:
        query += " AND body LIKE ?"
        params.append(f"%{keyword}%")
    
    if sender:
        query += " AND sender LIKE ?"
        params.append(f"%{sender}%")
        
    query += " ORDER BY timestamp DESC LIMIT ?"
    params.append(limit)

    try:
        with _get_db() as conn:
            cursor = conn.execute(query, params)
            results = [dict(row) for row in cursor.fetchall()]
            for r in results:
                r["data_type"] = "message"
                r["text"] = f"Message from {r.get('sender')} to {r.get('receiver')}: {r.get('body')}"
            logger.info(f"Tool `search_messages` found {len(results)} records")
            return results
    except Exception as e:
        logger.error(f"Tool execution failed: {e}")
        return []


def count_records(case_ids: List[str], record_type: str) -> Dict[str, Any]:
    """
    Count the total number of records of a specific type.
    
    Args:
        case_ids: List of case IDs.
        record_type: 'contact', 'message', 'call', 'location', 'media'.
        
    Returns:
        Dict with 'count' and 'type'.
    """
    valid_tables = {"contact": "contacts", "message": "messages", "call": "calls", "location": "locations", "media": "media"}
    table = valid_tables.get(record_type.lower().rstrip("s"))
    
    if not table:
        return {"error": f"Invalid record type: {record_type}"}

    query = f'SELECT COUNT(*) as count FROM "{table}" WHERE case_id IN ({",".join("?" * len(case_ids))})'
    
    try:
        with _get_db() as conn:
            cursor = conn.execute(query, list(case_ids))
            count = cursor.fetchone()["count"]
            logger.info(f"Tool `count_records` result: {count}")
            return {"count": count, "type": record_type, "data_type": "statistics", "text": f"Found {count} {record_type}s"}
    except Exception as e:
        logger.error(f"Tool execution failed: {e}")
        return {"error": str(e)}


def get_case_summary(case_ids: List[str]) -> List[Dict[str, Any]]:
    """Get metadata summary for cases."""
    # This is a placeholder for a more complex summary if needed
    # For now, it just returns case info if we had a cases table
    # But we can query distinct counts from other tables
    return []
